/* 
 * File:   eeprom.h
 * Author: gadis
 *
 * Created on July 6, 2017, 11:59 AM
 */

#ifndef EEPROM_H
#define	EEPROM_H

#ifdef	__cplusplus
extern "C" {
#endif

#include "projMain.h"
    
#define EEPROM_ADDRESS_TIME_ZONE 0x00
#define EEPROM_ADDRESS_DAY_LIGHT_START 0x02
#define EEPROM_ADDRESS_DAY_LIGHT_END 0x04
#define EEPROM_ADDRESS_CENTURY 0x06
#define EEPROM_ADDRESS_CYCLE_DELAY 0x07
#define EEPROM_ADDRESS_BLINK_ON_TIME 0x09
#define EEPROM_ADDRESS_BLINK_OFF_TIME 0x0A
#define EEPROM_ADDRESS_BLINK_LAST_X_SECONDS 0x0B
#define EEPROM_ADDRESS_AUDIO_NORMAL_ON_TIME 0x0C
#define EEPROM_ADDRESS_AUDIO_NORMAL_OFF_TIME 0x0D
#define EEPROM_ADDRESS_AUDIO_SPECIAL_ON_TIME 0x0E
#define EEPROM_ADDRESS_AUDIO_SPECIAL_OFF_TIME 0x0F
#define EEPROM_ADDRESS_SPECIAL_AUDIO_LAST_X_SECONDS 0x10
#define EEPROM_ADDRESS_GPS_SYNC_AT_START 0x11
#define EEPROM_ADDRESS_GPS_SYNC_EVERY_x_SECONDS 0x12
#define EEPROM_ADDRESS_GPS_SYNC_EVERY_DAY_AT_LOCAL_TIME 0x15
#define EEPROM_ADDRESS_AUDIO_NORMAL 0x17
#define EEPROM_ADDRESS_AUDIO_SPECIAL 0x2B
#define EEPROM_ADDRESS_CYCLE_TYPES 0x3F
#define EEPROM_ADDRESS_EVENTS 0x50
#define EEPROM_ADDRESS_STATES 0xE0

    
UINT8 extern CENTURY, BLINK_ON_TIME, BLINK_OFF_TIME, BLINK_LAST_X_SECONDS, AUDIO_NORMAL_ON_TIME, AUDIO_NORMAL_OFF_TIME, AUDIO_SPECIAL_ON_TIME, AUDIO_SPECIAL_OFF_TIME, SPECIAL_AUDIO_LAST_X_SECONDS, GPS_SYNC_AT_START;
INT16 extern TIME_ZONE, CYCLE_DELAY;
GSK_YEAR_DAY extern DAY_LIGHT_START, DAY_LIGHT_END;
GSK_SECOND_IN_DAY extern GPS_SYNC_EVERY_x_SECONDS, GPS_SYNC_EVERY_DAY_AT_LOCAL_TIME;

BYTE ReadEeprom (WORD_VAL Address);
void WriteEeprom (UINT16 Add, BYTE Data);
void LoadSettingsFromEeprom (void);
void LoadEventsFromEeprom (void);
void LoadStatesFromEeprom (void);
void LoadCyclesFromEeprom (void); // It should be always called after the function LoadStatesFromEeprom().
void LoadAllFromEeprom (void);

#ifdef	__cplusplus
}
#endif

#endif	/* EEPROM_H */

