/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.Component;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author gadis
 */
public class PlotHere extends javax.swing.JFrame {
    private Object windowEvent;

    /**
     * Creates new form PlotHere
     */
    public PlotHere(String Title) {
        initComponents();
        XYSeries Input00 = new XYSeries("Input 00");
        XYSeries Input01 = new XYSeries("Input 01");
        XYSeries Input02 = new XYSeries("Input 02");
        XYSeriesCollection data = new XYSeriesCollection(Input00);
        data.addSeries(Input01);
        data.addSeries(Input02);
        JFreeChart chart = ChartFactory.createXYLineChart(
            Title,
            "Angle",
            "Voltage",
            data,
            PlotOrientation.VERTICAL,
            true,
            true,
            false);
        ChartPanel chartpanel = new ChartPanel(chart);
        //chartpanel.setDomainZoomable(true);
        chartpanel.setPreferredSize(new java.awt.Dimension(200, 200));
        
        //JPanel jPanel4 = new JPanel();
        
        Component[] a = GraphHerePanel.getComponents();
        if (a.length==0) {
            GraphHerePanel.setLayout(new BorderLayout());
            GraphHerePanel.add(chartpanel);
        }
        this.revalidate();
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GraphHerePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        javax.swing.GroupLayout GraphHerePanelLayout = new javax.swing.GroupLayout(GraphHerePanel);
        GraphHerePanel.setLayout(GraphHerePanelLayout);
        GraphHerePanelLayout.setHorizontalGroup(
            GraphHerePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        GraphHerePanelLayout.setVerticalGroup(
            GraphHerePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GraphHerePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GraphHerePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    public void PutPoint(int key, double x, double y){
        Component[] a = GraphHerePanel.getComponents();
        ChartPanel chartpanel= (ChartPanel) a[0];
        JFreeChart chart = chartpanel.getChart();
        
        XYPlot plot = (XYPlot) chart.getPlot();
        XYSeriesCollection  data = (XYSeriesCollection) plot.getDataset();
        XYSeries XYseries = data.getSeries(key);
        XYseries.add(x,y);
                this.revalidate();
        this.repaint();

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlotHere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlotHere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlotHere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlotHere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlotHere("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GraphHerePanel;
    // End of variables declaration//GEN-END:variables
}
